# Generated by Django 6.0.2 on 2026-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
