# Generated by Django 6.0.2 on 2026-03-02 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer')], default='client', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('lawyer', 'appointment_date', 'appointment_time')},
        ),
    ]
