# Generated by Django 6.0.2 on 2026-04-08 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_aichat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('welcome', 'Welcome'), ('category_selection', 'Category Selection'), ('lawyer_selection', 'Lawyer Selection'), ('date_selection', 'Date Selection'), ('time_selection', 'Time Selection'), ('confirmation', 'Confirmation'), ('completed', 'Completed')], default='welcome', max_length=20)),
                ('selected_category', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_lawyer_id', models.IntegerField(blank=True, null=True)),
                ('selected_date', models.DateField(blank=True, null=True)),
                ('selected_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
