# Generated by Django 6.0.2 on 2026-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_aiconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
