# Generated by Django 6.0.2 on 2026-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_appointment_reschedule_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
