# Generated by Django 6.0.2 on 2026-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='state',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('lawyer_selection', 'Lawyer Selection'), ('date_selection', 'Date Selection'), ('time_selection', 'Time Selection'), ('confirmation', 'Confirmation'), ('completed', 'Completed')], default='welcome', max_length=20),
        ),
    ]
