# Generated by Django 5.2.14 on 2026-05-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_aiconversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
