# Generated by Django 6.0.2 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_aadhar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aadhar_number',
        ),
    ]
